apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.alpha.wavecat.net
spec:
  group: alpha.wavecat.net
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
      - db
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [name, username, password]
              properties:
                # Input
                name:
                  type: string
                  description: The name for the database.
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: Cannot rename databases
                username:
                  type: string
                  description: The name for the database's admin user.
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: Cannot rename admins
                password:
                  type: object
                  properties:
                    secretName:
                      type: string
                      description: The secret to load the password to be set from.
                      x-kubernetes-validations:
                        - rule: "self == oldSelf"
                          message: Cannot change secretNames
                    key:
                      type: string
                      description: The key to set in the secret.
                      x-kubernetes-validations:
                        - rule: "self == oldSelf"
                          message: Cannot change secret keys
                connectionUrl:
                  type: object
                  required: [secretName]
                  properties:
                    secretName:
                      type: string
                      description: The secret to create (or update) with the connection URL string.
                      x-kubernetes-validations:
                        - rule: "self == oldSelf"
                          message: Cannot change secretNames
                    key:
                      type: string
                      description: The key to set in the secret.
                      x-kubernetes-validations:
                        - rule: "self == oldSelf"
                          message: Cannot change secret keys
