apiVersion: wavecat.net/v1
kind: Database
metadata:
  name: my-db
spec:
  name: mydb
  username: myadmin
  password:
    secretName: mydbpassword
    key: password
  connectionUrl:
    secretName: mydb-creds
    key: url